apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong-database
  namespace: kong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kong-database
  template:
    metadata:
      labels:
        app: kong-database
    spec:
      containers:
      - name: postgres
        image: postgres:9.6
        env:
        - name: POSTGRES_USER
          value: "kong"
        - name: POSTGRES_DB
          value: "kong"
        - name: POSTGRES_PASSWORD
          value: "kong"
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: kong-database
  namespace: kong
spec:
  selector:
    app: kong-database
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432